=== VictorLopezGarcia/Lenguaje-de-Marcas/xsd/T3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="garderia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="neno" minOccurs="1" maxOccurs="50" type="tipoNeno"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="tipoNeno">
        <xs:sequence>
            <xs:element name="nome" type="tipoNome"/>
            <xs:element name="dataNacemento" type="xs:date"/>
            <xs:element name="peso" type="tipoPeso"/>
            <xs:element name="altura" type="xs:unsignedByte"/>
            <xs:element name="vacunas" type="xs:boolean"/>
            <xs:element ref="sexo" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="contacto" maxOccurs="4"/>
            <xs:element ref="idade"/>
        </xs:sequence>
        <xs:attribute name="numeroExpedente" type="xs:unsignedShort"/>
        <xs:attribute name="codigo" type="tipoCodigo"/>

    </xs:complexType>

    <xs:element name="sexo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="tipoSexo"/>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipoSexo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="H"/>
            <xs:enumeration value="M"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoPeso">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoNome">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="80"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCodigo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[PM][3-7]{2}(-[0-9]{3})?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="contacto">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="numero">
                    <xs:attribute name="relacion" type="tiporelacion" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="numero">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tiporelacion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pai"/>
            <xs:enumeration value="nai"/>
            <xs:enumeration value="avoa"/>
            <xs:enumeration value="avÃ³"/>
            <xs:enumeration value="titor"/>
            <xs:enumeration value="outra"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="idade">
        <xs:complexType>
            <xs:attribute name="anos" type="tipoAnos" use="required"/>
            <xs:attribute name="meses" type="tipomes" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="tipoAnos">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipomes">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="11"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== VictorLopezGarcia/Lenguaje-de-Marcas/xsd/T3.xml
<?xml version="1.0" encoding="UTF-8"?>

<garderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="T3.xsd">
    <neno numeroExpedente="2344" codigo="M53-123">
        <nome>Noa Blanco Coello</nome>
        <dataNacemento>2010-10-12</dataNacemento>
        <peso>13.5</peso>
        <altura>78</altura>
        <vacunas>true</vacunas>
        <sexo>M</sexo>
        <contacto relacion="pai">981123456</contacto>
        <contacto relacion="nai">981654321</contacto>
        <idade anos="2" meses="8"/>
    </neno>
</garderia>
